[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # ⚠️ Supabase-Instanz existiert nicht mehr - App läuft mit lokalen Mock-Daten
  # REACT_APP_SUPABASE_URL = "https://ihr-neues-supabase-projekt.supabase.co"
  # REACT_APP_SUPABASE_ANON_KEY = "ihr-neuer-anon-key"
  
  # Dummy-Werte für lokalen Modus (App erkennt diese und verwendet Mock-Daten)
  REACT_APP_SUPABASE_URL = "https://dummy.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "dummy-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache-Optimierung für bessere Performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
