[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Diese Werte werden in Netlify Dashboard als Environment Variables gesetzt
  # REACT_APP_SUPABASE_URL = "https://ihre-neue-supabase-url.supabase.co"
  # REACT_APP_SUPABASE_ANON_KEY = "ihr-neuer-anon-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache-Optimierung für bessere Performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
