name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        # App will detect dummy URLs and use local mode
        REACT_APP_SUPABASE_URL: "https://dummy.supabase.co"
        REACT_APP_SUPABASE_ANON_KEY: "dummy-key"
        CI: false
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main'
      with:
        name: build-files-${{ github.sha }}
        path: build/
        retention-days: 7
        
    - name: Build success
      run: |
        echo "✅ Build successful!"
        echo "📦 Artifacts uploaded"
        echo "🚀 Ready for deployment"
        echo "💡 Netlify will auto-deploy with real Supabase URLs"